### ISSUE TITLE
Uses tslib without depending on it

### ISSUE THREAD

**Issue by runeh** [bjerkio/fiken-js#3]
The tsconfig sets ` "importHelpers": true,`, which causes the emitted js code to use the `tslib` library. However, the package.json does not include a dependency on `tslib`. Projects that use `fiken-js` but don't use `tslib` will crash on startup.

**Comment by runeh** [comment]
I'm thinking it makes the most sense to set importHelpers to false? This lib will not be used so much in browsers, so bundle size isn't all that important?

**Comment by simenandre** [comment]
I agree. AFAIK, this doesn't need to be a major bump either. Wanna push a PR on it?
